apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-05-14T14:04:04Z
  name: alex-csv-demo.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://k8s-test/alex-csv-demo.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west-2a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.9
  masterPublicName: api.alex-csv-demo.k8s.local
  networkCIDR: 10.0.0.0/16
  networkID: vpc-foo
  networking:
    kopeio: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.0.8.0/22
    id: subnet-foo
    name: us-west-2a
    type: Private
    zone: us-west-2a
  - cidr: 10.0.0.0/22
    id: subnet-bar
    name: utility-us-west-2a
    type: Utility
    zone: us-west-2a
  topology:
    dns:
      type: Public
    masters: private
    nodes: private
